media: images

content:
  - name: pages
    label: pages
    path: pagesmd
    type: collection
    fields:
      - {name: title, label: Title, type: string}
      - {name: layout, type: string, hidden: true, default: post}
      - {name: description, label: Description, type: string, options: { maxlength: 160}}
      - { name: image, label: Image, type: image }
      - { name: body, label: Body, type: rich-text}

      # ... fields defined here ..
