media: images

content:
  - name: pages
    label: pages
    path: pagesmd
    type: collection
    fields:
      - name: cover
        label: Cover Image
        type: image
      # ... fields defined here ...
