media: images

content:
  - name: pages
    label: pages
    path: pagesmd
    type: collection
    fields:
      - { name: title, label: header, type: rich-text }
      - {
          name: description,
          label: Description,
          type: string,
          options: { maxlength: 160 },
        }
      - { name: body, label: Body, type: rich-text }

      # ... fields defined here ..
